### ISSUE TITLE
Question about train_a3gc_tp.py

### ISSUE THREAD

**Issue by huzijun1996** [trikpachu/A3GC-IP#3]
I use a half-precision approach for training:
python3 train_a3gc_tp.py -b 16 --name A3GC___ --lr 1e-3 --hu1 256 --hu2 64 --hu3 128 --norm --cda --start_at 1 --half

However, an error occurred:
Traceback (most recent call last):
  File "train_a3gc_tp.py", line 317, in <module>
    main()
  File "train_a3gc_tp.py", line 231, in main
    model.half()
NameError: name 'model' is not defined

The error in the code:
    if args.half:
        model.half()
        criterion.half()

If I change the code to:
    if args.half:
        model1.half()
        criterion1.half()

Errors may also occur:
Traceback (most recent call last):
  File "train_a3gc_tp.py", line 317, in <module>
    main()
  File "train_a3gc_tp.py", line 232, in main
    criterion1.half()
  File "/home/xxx/anaconda3/envs/a3gc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1007, in half
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
  File "/home/xxx/anaconda3/envs/a3gc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 801, in _apply
    for module in self.children():
  File "/home/xxx/anaconda3/envs/a3gc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2283, in children
    for name, module in self.named_children():
  File "/home/xxx/anaconda3/envs/a3gc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2301, in named_children
    for name, module in self._modules.items():
  File "/home/xxx/anaconda3/envs/a3gc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'pose_loss' object has no attribute '_modules'

Should the code be changed to the following format?No longer consider the issue of criterion?
if args.half:
    model1.half()
    model2.half()
    model3.half()

**Comment by trikpachu** [comment]
As stated in a previous answer, there was also a problem when using .half() on my machine (originally I never used it). I never tracked down the issue and won't have time to do it now. So unfortunately the code is only usable in full precision (without --half). Your first error is simply caused by the variable "model" not existing. For your second error I am not sure, as I also rarely use half precision in general and don't know by head what pytorch needs to make it work. Maybe everything has to be set to half precision to make it work (I can imagine aan error when putting fp16 and fp32 in a calculation together). It could also be possible that additional stuff has to be put in the custom layers to make it work.

**Comment by huzijun1996** [comment]
I have already tried that modification is not feasible and the loss will not converge. I will consider other possibilities.

Thank you for your answer.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "trikpachu/A3GC-IP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 晚上8:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [trikpachu/A3GC-IP] Question about train_a3gc_tp.py (Issue #3)





 
As stated in a previous answer, there was also a problem when using .half() on my machine (originally I never used it). I never tracked down the issue and won't have time to do it now. So unfortunately the code is only usable in full precision (without --half). Your first error is simply caused by the variable "model" not existing. For your second error I am not sure, as I also rarely use half precision in general and don't know by head what pytorch needs to make it work. Maybe everything has to be set to half precision to make it work (I can imagine aan error when putting fp16 and fp32 in a calculation together). It could also be possible that additional stuff has to be put in the custom layers to make it work.
